export const skillsCatalog = [
  {
    id: "rag-answering",
    name: "RAG 回答策略",
    category: "回答策略",
    status: "已启用",
    badgeTone: "ready",
    description: "围绕检索结果生成更稳定的回答结构，适合收藏检索和知识问答。",
    highlights: ["强调来源感知", "控制总结粒度", "适合视频知识库"],
    ctaLabel: "当前使用中",
    disabled: true,
  },
  {
    id: "summary-composer",
    name: "摘要编排器",
    category: "内容整理",
    status: "可用",
    badgeTone: "available",
    description: "把长视频内容整理成更紧凑的知识卡片、摘要和行动清单。",
    highlights: ["长内容压缩", "章节提要", "便于二次阅读"],
    ctaLabel: "即将接入",
    disabled: true,
  },
  {
    id: "dialog-operator",
    name: "会话操作员",
    category: "对话工作流",
    status: "规划中",
    badgeTone: "planned",
    description: "帮助你按目标拆解问题、维护连续追问，并把多轮对话沉淀成可复用结论。",
    highlights: ["连续追问", "会话沉淀", "结果复用"],
    ctaLabel: "规划中",
    disabled: true,
  },
  {
    id: "research-brief",
    name: "研究简报",
    category: "知识产出",
    status: "规划中",
    badgeTone: "planned",
    description: "把多个视频或收藏夹的内容压成一页式简报，突出关键观点与差异。",
    highlights: ["多视频汇总", "差异对照", "可导出报告"],
    ctaLabel: "规划中",
    disabled: true,
  },
  {
    id: "qa-router",
    name: "问答路由器",
    category: "系统能力",
    status: "规划中",
    badgeTone: "planned",
    description: "在回答前判断应该走单视频、收藏夹、全局知识库还是总结式流程。",
    highlights: ["作用域决策", "减少误答", "利于后续扩展"],
    ctaLabel: "规划中",
    disabled: true,
  },
  {
    id: "writer-mode",
    name: "写作模式",
    category: "知识产出",
    status: "规划中",
    badgeTone: "planned",
    description: "针对整理过的视频知识自动输出教程、提纲、备忘录和复盘文稿。",
    highlights: ["教程生成", "提纲输出", "适合个人沉淀"],
    ctaLabel: "规划中",
    disabled: true,
  },
];
