export const toolsCatalog = [
  {
    id: "workspace-filesystem",
    name: "工作区文件系统",
    category: "开发工具",
    status: "可用",
    badgeTone: "available",
    description: "在隔离 workspace 内执行目录浏览、文件读取、写入、追加与目录创建等操作。",
    highlights: ["工作区隔离", "文件读写", "审批可控"],
    ctaLabel: "已接入面板",
    disabled: true,
  },
  {
    id: "workspace-command-runner",
    name: "工作区命令执行器",
    category: "开发工具",
    status: "可用",
    badgeTone: "available",
    description: "通过 local runtime 或 Docker sandbox 在工作区内执行命令，为 agent 工具调用提供底层执行能力。",
    highlights: ["本地运行时", "Docker 沙箱", "策略控制"],
    ctaLabel: "已接入面板",
    disabled: true,
  },
  {
    id: "web-search",
    name: "网页搜索",
    category: "外部连接",
    status: "可用",
    badgeTone: "available",
    description: "直接给 agent 返回结构化网页搜索结果，适合先补充最新信息，再结合收藏夹内容写文案或导出页面。",
    highlights: ["结构化结果", "标题+链接+摘要", "适合 skill 调用"],
    ctaLabel: "已接入面板",
    disabled: true,
  },
  {
    id: "bilibili-sync",
    name: "B 站收藏同步器",
    category: "内容处理",
    status: "已接入",
    badgeTone: "ready",
    description: "同步收藏夹和视频元数据，把外部内容拉回工作台作为检索入口。",
    highlights: ["收藏夹同步", "视频元数据", "现已可用"],
    ctaLabel: "已接入",
    disabled: true,
  },
  {
    id: "transcript-pipeline",
    name: "转写流水线",
    category: "内容处理",
    status: "已接入",
    badgeTone: "ready",
    description: "管理音频保留、转写、摘要与重置，支撑收藏检索页的内容加工能力。",
    highlights: ["音频保留", "转写与摘要", "重置处理"],
    ctaLabel: "已接入",
    disabled: true,
  },
  {
    id: "vector-index",
    name: "向量索引器",
    category: "检索增强",
    status: "已接入",
    badgeTone: "ready",
    description: "负责把已处理内容写入检索层，为单视频、收藏夹和全局问答提供召回基础。",
    highlights: ["分段索引", "检索召回", "面向 RAG"],
    ctaLabel: "已接入",
    disabled: true,
  },
  {
    id: "bili-discovery",
    name: "B 站视频发现器",
    category: "外部连接",
    status: "可用",
    badgeTone: "available",
    description: "根据当前收藏夹主题去 B 站补充候选视频，作为收藏扩展和二次筛选入口。",
    highlights: ["关联搜索", "分页浏览", "后续可接一键收藏"],
    ctaLabel: "已内置在收藏检索",
    disabled: true,
  },
  {
    id: "evaluation-kit",
    name: "评测工具包",
    category: "实验工具",
    status: "可用",
    badgeTone: "available",
    description: "为 RAG 问答提供离线评测、实验矩阵和结果比对能力。",
    highlights: ["离线评测", "实验矩阵", "结果回放"],
    ctaLabel: "已内置后端",
    disabled: true,
  },
  {
    id: "document-exporter",
    name: "文档导出器",
    category: "知识产出",
    status: "规划中",
    badgeTone: "planned",
    description: "把摘要、问答和多视频整理结果导出成可沉淀的文档资产。",
    highlights: ["摘要导出", "报告归档", "便于复盘"],
    ctaLabel: "规划中",
    disabled: true,
  },
];
